language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - "pip install -U setuptools pip"
  - "pip install -r requirements.txt"
  - "pip install 'coverage<4'"
  - "pip install coveralls"
# command to run tests
# running the test twice isn't very efficient but it does work
script:
  - coverage run --source dhcp_leases setup.py test
  - python setup.py test
after_success: coveralls
